### ISSUE TITLE
Freez while in dungeon

### ISSUE THREAD

**Issue by suz-png** [Macumbatbc/flyPlateBuffs-WOTLKC#1]
Hi ,thanks for your work ! i have some freeze while i'm in dungeons using this addon (probably because of the amount of mobs) , is there any way to fix it ? have a good day !

**Comment by Macumbatbc** [comment]
Hello, those bug was already in the tbc version afaik.
This addon is mainly made for PvP.
I advice you this alternative for pve 
NameplateAura
https://www.curseforge.com/wow/addons/nameplateauras

Also, are you sure it's this addon which make you freeze? 
Do you have some errors with it? If yes, share a screen of it please.

**Comment by suz-png** [comment]
thank you for your answer, i dont know how to check errors... but i still have some issues without flyplatebuff . probably something else

**Comment by Macumbatbc** [comment]
Could be an other addon conflicting with it.
Try once with all other addons disabled and check how it is.

**Comment by suz-png** [comment]
ok the problem is mainly from kiwi farm and it worse with flyplatebuffs, it make sens because its not an addon for pve and a large number of nameplate i guess. thanks for your help
